### ISSUE TITLE
DEUX-CENT-ZÉRO 😁

### ISSUE THREAD

**Issue by Geolim4** [fjobeir/french-numbers-to-words#1]
Salut,

J'ai trouvé ta lib sympa, mais j'ai vu un petit bug avec les nombres de centaines ronds:
200, 300, etc :)

Merci bien !

**Comment by Geolim4** [comment]
Ah bah d'ailleurs il y a eu sûrement une belle régression 😅

![image](https://github.com/fjobeir/french-numbers-to-words/assets/1332071/efb4b6e1-944e-4f43-bb9e-980c46e4890e)

**Comment by fjobeir** [comment]
Bonjour @Geolim4 
Merci d'avoir installé et signalé le problème. Je l'ai corrigé et honnêtement, je prévois de refactoriser l'ensemble du package, au moins il devrait être en TypeScript

**Comment by Geolim4** [comment]
Top merci bien :D

**Comment by Geolim4** [comment]
Tu as push l'update sur NPM ?

**Comment by fjobeir** [comment]
Oui, la nouvelle version est la 0.1.7
