### ISSUE TITLE
Wrong plural on the word thousand

### ISSUE THREAD

**Issue by AaronActu** [fjobeir/french-numbers-to-words#4]
### Problem
I noticed that the word "mille" was tuned, but it is invariable and should therefore never have the plural mark 's'

### Solution
I created two pull requests to fix this issue : 

1. [patch-1](https://github.com/fjobeir/french-numbers-to-words/pull/3): fix the code to remove the 's'
3. [patch-2](https://github.com/fjobeir/french-numbers-to-words/pull/2): fix the explanations and the examples in the README

#### Source
https://www.projet-voltaire.fr/regles-orthographe/mille-ou-milles/

**Comment by fjobeir** [comment]
Thanks for your input @AaronActu
