### ISSUE TITLE
Badly converted power of tens

### ISSUE THREAD

**Issue by AaronActu** [fjobeir/french-numbers-to-words#5]
### Problem

While reworking the project to create the typescript version, I added some jest test. It turns out that 1000 is badly converted to  "un-mille zéro". The same problem applies to other powers of ten (10 000 --> "dix-mille zéro", etc...)

### Troubleshooting

It might be caused by separating the originial number into groups of 3 digits.
The first group, here: "1" is converted as "un" with unit "mille" --> "un-mille"
The second group: "000" converted to 0, is then interpreted to "zéro"

#### How would you like to manage this case ?

**Comment by fjobeir** [comment]
Hey @AaronActu Thanks for testing and giving a feedback.
I have posted a fix. Hopefully it is going to give the correct result
